# Generated by Django 3.2.11 on 2022-04-16 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods_container', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='name',
            field=models.CharField(default='hi', max_length=50, verbose_name='container name'),
        ),
    ]
