# Generated by Django 3.2.11 on 2022-04-16 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods_container', '0003_auto_20220416_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='container',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
