# Generated by Django 3.2.11 on 2022-04-17 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods_container', '0004_auto_20220416_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='memo',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Memo'),
        ),
    ]
